# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.cache/wt [current_project]
set_property parent.project_path D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1.xci
set_property is_locked true [get_files d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cordic_1 -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all cordic_1_

write_checkpoint -force -noxdef cordic_1.dcp

catch { report_utilization -file cordic_1_utilization_synth.rpt -pb cordic_1_utilization_synth.pb }

if { [catch {
  file copy -force D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.runs/cordic_1_synth_1/cordic_1.dcp d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.ip_user_files/ip/cordic_1]} {
  catch { 
    file copy -force d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_stub.v D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.ip_user_files/ip/cordic_1
  }
}

if {[file isdir D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.ip_user_files/ip/cordic_1]} {
  catch { 
    file copy -force d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1_stub.vhdl D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC/EE2020_myDAC.ip_user_files/ip/cordic_1
  }
}
