# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.cache/wt} [current_project]
set_property parent.project_path {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1.dcp}}
set_property used_in_implementation false [get_files {{d:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/ip/cordic_1/cordic_1.dcp}}]
read_verilog -library xil_defaultlib {
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/d_flipflop.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/BCD.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_hi_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_sin_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider_custom_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_trapezium_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_sawtooth_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/ssd_controller.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/ssd.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_sine_AM.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/operation_invert_vertical.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/operation_squarefy_invert.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/operation_squarefy.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/display_freq_n_amp.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_half_rectified_sine.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider_samp.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider_ssd.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_tri_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/debouncer.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_square_wave.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider_slower.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider_half.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/clock_divider.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/change_wave_freq.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/change_wave_amp.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/alphanum_mux.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/new/gen_exp_bound_sine.v}
  {D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/imports/sources_1/new/myDAC_TOP.v}
}
read_vhdl -library xil_defaultlib {{D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/sources_1/imports/sources_1/imports/SourceFiles/DA2RefComp.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/constrs_1/imports/_solution_files/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Desktop/MyWork/EE2020_myDAC_square_gen_working.xpr/EE2020_myDAC_monday morning.xpr/EE2020_myDAC/EE2020_myDAC.srcs/constrs_1/imports/_solution_files/Basys3_Master.xdc}}]


synth_design -top myDAC_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef myDAC_TOP.dcp

catch { report_utilization -file myDAC_TOP_utilization_synth.rpt -pb myDAC_TOP_utilization_synth.pb }
